Repository ArkEcosystem/platform-sdk, pull requests merged in 2021-03, with the labels that each got.

#1118 fix(cli): ensure transaction amount is greater than 0
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-cli/src/commands/create-wallet.ts
  packages/platform-sdk-cli/src/commands/send-transaction.ts
Labels: Complexity: Low, Status: Needs Review

#1119 release: 3.0.31
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Status: Needs Review

#1120 chore: update lockfile
  .yarn/install-state.gz
  yarn.lock
Labels: Complexity: Low, Status: Needs Review

#1121 feat(cli): implement storage persistence
  .pnp.js
  .yarn/cache/ajv-formats-npm-1.5.1-f058cf5c41-0c13847af1.zip
  .yarn/cache/ajv-npm-7.1.1-2207905505-fe4e138529.zip
  .yarn/cache/atomically-npm-1.7.0-e742e5293b-a1e519d531.zip
  .yarn/cache/conf-npm-9.0.2-e327d2389b-da16e2eb26.zip
  .yarn/cache/debounce-fn-npm-4.0.0-fc4e97bcb1-290c4ac231.zip
  .yarn/cache/dot-prop-npm-6.0.1-de66211710-06793b8680.zip
  .yarn/cache/json-schema-traverse-npm-1.0.0-fb3684f4f0-7a230bcd92.zip
  .yarn/cache/json-schema-typed-npm-7.0.3-b2c25a2ec3-0b7e77f321.zip
  .yarn/cache/pkg-up-npm-3.1.0-1eebe033b7-df82763250.zip
  .yarn/install-state.gz
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-cli/src/commands/access-profile.ts
  packages/platform-sdk-cli/src/commands/access-wallet.ts
  packages/platform-sdk-cli/src/commands/create-profile.ts
  packages/platform-sdk-cli/src/commands/create-wallet.ts
  packages/platform-sdk-cli/src/helpers.ts
  packages/platform-sdk-cli/src/storage.ts
  yarn.lock
Labels: Complexity: High, Status: Needs Review

#1122 feat(cli): list transactions for active wallet
  .yarn/build-state.yml
  .yarn/install-state.gz
  packages/platform-sdk-cli/src/commands/access-wallet.ts
  packages/platform-sdk-cli/src/commands/list-transactions.ts
Labels: Complexity: High, Status: Needs Review

#1123 feat(cli): ask for an optional password during profile creation
  packages/platform-sdk-cli/src/commands/access-profile.ts
  packages/platform-sdk-cli/src/commands/access-wallet.ts
  packages/platform-sdk-cli/src/commands/change-password.ts
  packages/platform-sdk-cli/src/commands/create-profile.ts
  packages/platform-sdk-cli/src/storage.ts
Labels: Complexity: Medium, Status: Needs Review

#1124 feat(eth-server): pagination for wallet transactions
  .yarn/build-state.yml
  .yarn/install-state.gz
  packages/platform-sdk-cli/src/commands/access-wallet.ts
  packages/platform-sdk-cli/src/commands/change-password.ts
  packages/platform-sdk-cli/src/commands/create-profile.ts
  packages/platform-sdk-cli/src/commands/list-transactions.ts
  packages/platform-sdk-eth-server/src/index.ts
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#1125 refactor(profiles): use internal and external transaction ID
  .pnp.js
  .yarn/install-state.gz
  codecov.yml
  packages/platform-sdk-ark/src/services/transaction.ts
  packages/platform-sdk-atom/src/services/client.ts
  packages/platform-sdk-atom/src/services/transaction.ts
  packages/platform-sdk-avax/src/dto/signed-transaction.ts
  packages/platform-sdk-avax/src/services/client.ts
  packages/platform-sdk-avax/src/services/transaction.ts
  packages/platform-sdk-egld/src/services/client.ts
  packages/platform-sdk-eth/src/services/client.ts
  packages/platform-sdk-neo/src/services/client.ts
  packages/platform-sdk-neo/src/services/transaction.ts
  packages/platform-sdk-profiles/src/wallets/wallet-transaction-service.test.ts
  packages/platform-sdk-profiles/src/wallets/wallet-transaction-service.ts
  packages/platform-sdk-sol/src/services/client.ts
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xlm/src/services/client.ts
  packages/platform-sdk-xlm/src/services/transaction.ts
  packages/platform-sdk-xrp/src/services/client.ts
  packages/platform-sdk/src/contracts/coins/data.ts
  packages/platform-sdk/src/dto/signed-transaction.test.ts
  packages/platform-sdk/src/dto/signed-transaction.ts
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review

#1126 feat(avax): implement `Address#fromPrivateKey` and `Keys#fromMnemonic`
  packages/platform-sdk-avax/src/networks/avax/mainnet.ts
  packages/platform-sdk-avax/src/networks/avax/testnet.ts
  packages/platform-sdk-avax/src/services/helpers.ts
  packages/platform-sdk-avax/src/services/identity.test.ts
  packages/platform-sdk-avax/src/services/identity/address.ts
  packages/platform-sdk-avax/src/services/identity/keys.ts
  packages/platform-sdk-avax/src/services/identity/private-key.ts
  packages/platform-sdk-avax/src/services/identity/public-key.ts
  packages/platform-sdk-avax/test/fixtures/identity.ts
Labels: Complexity: High, Status: Needs Review

#1127 chore(cli): register more coin implementations
  packages/platform-sdk-avax/src/services/helpers.ts
  packages/platform-sdk-cli/src/commands/create-wallet.ts
  packages/platform-sdk-cli/src/helpers.ts
Labels: Complexity: Medium, Status: Needs Review

#1128 chore: fix eslint
  .eslintignore
  .eslintrc.json
  .github/workflows/cf.yml
  package.json
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc-server/src/helpers.ts
  packages/platform-sdk-btc-server/src/index.ts
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-cli/src/helpers.ts
  packages/platform-sdk-cli/src/index.ts
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot-indexer/src/helpers.ts
  packages/platform-sdk-dot-indexer/src/index.ts
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-egld/src/services/client.ts
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-sol/src/services/client.ts
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Low, Status: Needs Review

#1129 feat(cli): show explorer link for confirmed transaction
  .pnp.js
  .yarn/install-state.gz
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/plugins/@yarnpkg/plugin-typescript.cjs
  .yarn/plugins/@yarnpkg/plugin-version.cjs
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarnrc.yml
  jest.coverage.js
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-cli/src/commands/create-profile.ts
  packages/platform-sdk-cli/src/commands/create-wallet.ts
  packages/platform-sdk-cli/src/commands/send-transaction.ts
  packages/platform-sdk-cli/src/helpers.ts
  packages/platform-sdk-profiles/src/wallets/wallet-transaction-service.test.ts
  packages/platform-sdk-profiles/src/wallets/wallet-transaction-service.ts
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review

#1130 chore: remove outdated TODO comments
  jest.coverage.js
  packages/platform-sdk-avax/src/dto/wallet.ts
  packages/platform-sdk-avax/src/services/client.ts
  packages/platform-sdk-btc-indexer/src/index.ts
  packages/platform-sdk-profiles/src/helpers/queue.ts
  packages/platform-sdk-profiles/src/repositories/wallet-repository.ts
  packages/platform-sdk-profiles/src/wallets/wallet.ts
Labels: Complexity: Low, Status: Needs Review

#1132 fix(profiles): dump stale wallet state if it has been partially restored
  packages/platform-sdk-profiles/src/dto/transaction-mapper.test.ts
  packages/platform-sdk-profiles/src/mappers/delegate-mapper.test.ts
  packages/platform-sdk-profiles/src/repositories/wallet-repository.test.ts
  packages/platform-sdk-profiles/src/repositories/wallet-repository.ts
  packages/platform-sdk-profiles/src/wallets/wallet-transaction-service.test.ts
  packages/platform-sdk-profiles/src/wallets/wallet.factory.ts
  packages/platform-sdk-profiles/src/wallets/wallet.test.ts
  packages/platform-sdk-profiles/src/wallets/wallet.ts
  packages/platform-sdk-profiles/test/helpers.ts
Labels: Complexity: Low, Status: Needs Review

#1133 fix(egld): fix coin name in manifest
  .yarn/build-state.yml
  .yarn/install-state.gz
  packages/platform-sdk-egld/src/manifest.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#1134 release: 3.0.40
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Status: Needs Review

#1139 chore: deprecate `platform-sdk-json-rpc`
  common/config/rush/pnpm-lock.yaml
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/LICENSE
  packages/platform-sdk-json-rpc/README.md
  packages/platform-sdk-json-rpc/banner.png
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-json-rpc/src/index.ts
  packages/platform-sdk-json-rpc/src/logger.ts
  packages/platform-sdk-json-rpc/src/methods.ts
  packages/platform-sdk-json-rpc/src/methods/fee.ts
  packages/platform-sdk-json-rpc/src/methods/identity.ts
  packages/platform-sdk-json-rpc/tsconfig.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
  rush.json
Labels: Complexity: High, Status: Needs Review

#1140 chore: enable pnpm workspaces
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/src/qrcode.test.ts
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
  rush.json
  scripts/version.sh
Labels: Complexity: Undetermined, Status: Needs Review

#1141 release: 3.0.41
  CHANGELOG.md
  README.md
  common/config/rush/.npmrc-publish
  common/config/rush/version-policies.json
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Undetermined, Status: Needs Review

#1142 chore: remove deprecated deps
  .prettierignore
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Low, Status: Needs Review

#1143 chore: set up `eslint-plugin-import`
  .eslintrc.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-crypto/src/bip38.ts
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-lsk/src/services/fee.ts
  packages/platform-sdk-lsk/src/services/message.ts
  packages/platform-sdk-lsk/src/services/transaction.ts
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-neo/src/services/client.ts
  packages/platform-sdk-neo/src/services/message.ts
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-profiles/src/plugins/plugin-registry.models.ts
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-support/src/censor.test.ts
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: High, Status: Needs Review

#1144 refactor(ada): use `@emurgo/cardano-serialization-lib-nodejs` for address derivation
  packages/platform-sdk-ada/src/crypto/shelley/address.ts
  packages/platform-sdk-ada/src/crypto/shelley/constants.ts
  packages/platform-sdk-ada/src/crypto/shelley/hdpath.ts
  packages/platform-sdk-ada/src/services/client.ts
  packages/platform-sdk-ada/src/services/identity/address.ts
  packages/platform-sdk-ada/src/services/identity/keys.ts
  packages/platform-sdk-ada/src/services/identity/shelley.ts
  packages/platform-sdk-ada/test/mariano.test.ts
Labels: Complexity: High, Status: Needs Review

#1146 fix(cli): skip actions if values are falsy
  packages/platform-sdk-cli/src/commands/access-profile.ts
  packages/platform-sdk-cli/src/commands/change-password.ts
  packages/platform-sdk-cli/src/commands/create-profile.ts
  packages/platform-sdk-cli/src/commands/create-wallet.ts
  packages/platform-sdk-cli/src/commands/send-transaction.ts
Labels: Complexity: Low, Status: Needs Review

#1145 chore: set up `eslint-plugin-tsdoc`
  .eslintrc.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Status: Needs Review

#1147 chore(cli): enable SOL integration
  packages/platform-sdk-cli/src/helpers.ts
Labels: Complexity: Low, Status: Needs Review

#1148 refactor: use enum to access configuration values
  packages/platform-sdk-ada/src/services/client.ts
  packages/platform-sdk-avax/src/services/client.ts
  packages/platform-sdk-avax/src/services/helpers.ts
  packages/platform-sdk-avax/src/services/message.ts
  packages/platform-sdk-avax/src/services/transaction.ts
  packages/platform-sdk-eos/src/services/transaction.ts
  packages/platform-sdk/src/coins/config.test.ts
  packages/platform-sdk/src/coins/config.ts
Labels: Complexity: Low, Status: Needs Review

#1150 feat(ada): implement `AddressListFactory`
  packages/platform-sdk-ada/src/services/identity/address-list.factory.ts
  packages/platform-sdk-ada/src/services/identity/keys.ts
  packages/platform-sdk-ada/src/services/identity/shelley.ts
Labels: Complexity: Medium, Status: Needs Review

#1153 chore(sol): update readme banner
  packages/platform-sdk-sol/banner.png
Labels: Complexity: Low, Type: Task

#1154 chore(egld): update readme banner
  packages/platform-sdk-egld/banner.png
Labels: Complexity: Low, Type: Task

#1152 feat: implement derivation feature flags
  packages/platform-sdk-ada/src/networks/ada/mainnet.ts
  packages/platform-sdk-ada/src/networks/ada/testnet.ts
  packages/platform-sdk-ark/src/networks/ark/devnet.ts
  packages/platform-sdk-ark/src/networks/ark/mainnet.ts
  packages/platform-sdk-ark/src/networks/compendia/mainnet.ts
  packages/platform-sdk-btc/src/networks/btc/livenet.ts
  packages/platform-sdk-btc/src/networks/btc/testnet.ts
  packages/platform-sdk-eth/src/networks/eth/goerli.ts
  packages/platform-sdk-eth/src/networks/eth/kovan.ts
  packages/platform-sdk-eth/src/networks/eth/mainnet.ts
  packages/platform-sdk-eth/src/networks/eth/rinkeby.ts
  packages/platform-sdk-eth/src/networks/eth/ropsten.ts
  packages/platform-sdk-lsk/src/networks/lsk/mainnet.ts
  packages/platform-sdk-lsk/src/networks/lsk/testnet.ts
  packages/platform-sdk-profiles/test/fixtures/network.json
  packages/platform-sdk/src/coins/enums.test.ts
  packages/platform-sdk/src/coins/enums.ts
  packages/platform-sdk/src/coins/network-repository.test.ts
  packages/platform-sdk/src/coins/network.models.ts
  packages/platform-sdk/src/coins/network.test.ts
Labels: Complexity: Medium, Status: Needs Review

#1155 refactor(sdk): make `AddressList#fromMnemonic` asynchronous
  packages/platform-sdk-ada/src/services/identity/address-list.test.ts
  packages/platform-sdk-ada/src/services/identity/address-list.ts
  packages/platform-sdk-ark/src/services/identity/address-list.ts
  packages/platform-sdk-atom/src/services/identity/address-list.ts
  packages/platform-sdk-avax/src/services/identity/address-list.ts
  packages/platform-sdk-btc/src/services/identity/address-list.ts
  packages/platform-sdk-dot/src/services/identity/address-list.ts
  packages/platform-sdk-egld/src/services/identity/address-list.ts
  packages/platform-sdk-eos/src/services/identity/address-list.ts
  packages/platform-sdk-eth/src/services/identity/address-list.ts
  packages/platform-sdk-lsk/src/services/identity/address-list.ts
  packages/platform-sdk-neo/src/services/identity/address-list.ts
  packages/platform-sdk-profiles/test/fixtures/network.json
  packages/platform-sdk-sol/src/services/identity/address-list.ts
  packages/platform-sdk-trx/src/services/identity/address-list.ts
  packages/platform-sdk-xlm/src/services/identity/address-list.ts
  packages/platform-sdk-xrp/src/services/identity/address-list.ts
  packages/platform-sdk/src/contracts/coins/identity.ts
Labels: Complexity: Low, Status: Needs Review

#1156 feat: implement `AddressList#fromPrivateKey`
  packages/platform-sdk-ada/src/services/identity/address-list.ts
  packages/platform-sdk-ark/src/services/identity/address-list.ts
  packages/platform-sdk-atom/src/services/identity/address-list.ts
  packages/platform-sdk-avax/src/services/identity/address-list.ts
  packages/platform-sdk-btc/src/services/identity/address-list.ts
  packages/platform-sdk-dot/src/services/identity/address-list.ts
  packages/platform-sdk-egld/src/services/identity/address-list.ts
  packages/platform-sdk-eos/src/services/identity/address-list.ts
  packages/platform-sdk-eth/src/services/identity/address-list.ts
  packages/platform-sdk-lsk/src/services/identity/address-list.ts
  packages/platform-sdk-neo/src/services/identity/address-list.ts
  packages/platform-sdk-sol/src/services/identity/address-list.ts
  packages/platform-sdk-trx/src/services/identity/address-list.ts
  packages/platform-sdk-xlm/src/services/identity/address-list.ts
  packages/platform-sdk-xrp/src/services/identity/address-list.ts
  packages/platform-sdk/src/contracts/coins/identity.ts
Labels: Complexity: Medium, Status: Needs Review

#1136 feat(profiles): implement profile importing and exporting
  packages/platform-sdk-profiles/src/profiles/profile.models.ts
  packages/platform-sdk-profiles/src/profiles/profile.test.ts
  packages/platform-sdk-profiles/src/profiles/profile.ts
  packages/platform-sdk-profiles/src/repositories/profile-repository.test.ts
  packages/platform-sdk-profiles/src/repositories/profile-repository.ts
  packages/platform-sdk-profiles/src/repositories/wallet-repository.ts
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#1159 fix(btc-server): add username and password flags
  packages/platform-sdk-btc-server/bin/meow.js
Labels: Complexity: Low, Status: Needs Review

#1160 refactor(crypto): allow passing in of a BIP44 purpose to support BIP49/84
  packages/platform-sdk-crypto/src/bip44.ts
Labels: Complexity: Low, Status: Needs Review

#1157 feat(profiles): support BIP39/44 derivation
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/platform-sdk-ada/src/services/client.ts
  packages/platform-sdk-ada/src/services/identity/address-list.ts
  packages/platform-sdk-ada/src/services/identity/address.ts
  packages/platform-sdk-ada/src/services/identity/keys.ts
  packages/platform-sdk-ada/src/services/identity/public-key.ts
  packages/platform-sdk-ada/src/services/identity/shelley.ts
  packages/platform-sdk-ada/test/mariano.test.ts
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-profiles/src/repositories/wallet-repository.ts
  packages/platform-sdk-profiles/src/wallets/wallet.factory.test.ts
  packages/platform-sdk-profiles/src/wallets/wallet.factory.ts
  packages/platform-sdk-profiles/test/helpers.ts
Labels: Complexity: High, Status: Needs Review

#1158 chore: update typescript to 4.2.2
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-markets/src/service.ts
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-profiles/src/environment/storage/factory.ts
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
  packages/platform-sdk/src/http/request.ts
  tsconfig.json
Labels: Complexity: Undetermined, Status: Needs Review

#1161 refactor(ada): use `@emurgo/cardano-serialization-lib-nodejs` for message signing
  packages/platform-sdk-ada/src/services/identity/keys.ts
  packages/platform-sdk-ada/src/services/message.ts
Labels: Complexity: Low, Status: Needs Review

#1162 refactor(ada): use `bech32` for address validation
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ada/src/services/identity/address.ts
  packages/platform-sdk-ada/src/services/message.ts
Labels: Complexity: Undetermined, Status: Needs Review

#1163 feat(btc): implement BIP49 and BIP84
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/platform-sdk-ada/src/services/identity/address.ts
  packages/platform-sdk-ada/src/services/identity/keys.ts
  packages/platform-sdk-atom/src/services/identity/address.ts
  packages/platform-sdk-atom/src/services/identity/keys.ts
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-btc/src/services/identity.test.ts
  packages/platform-sdk-btc/src/services/identity/address.ts
  packages/platform-sdk-btc/src/services/identity/utils.ts
  packages/platform-sdk-btc/test/fixtures/identity.ts
  packages/platform-sdk-eth/src/services/identity/address.ts
  packages/platform-sdk-eth/src/services/identity/keys.ts
  packages/platform-sdk-eth/src/services/identity/private-key.ts
  packages/platform-sdk-neo/src/services/identity/address.ts
  packages/platform-sdk-neo/src/services/identity/keys.ts
  packages/platform-sdk-neo/src/services/identity/private-key.ts
  packages/platform-sdk-neo/src/services/identity/public-key.ts
  packages/platform-sdk-neo/src/services/identity/wif.ts
  packages/platform-sdk-sol/src/services/identity/address.ts
  packages/platform-sdk-sol/src/services/identity/keys.ts
  packages/platform-sdk-sol/src/services/identity/private-key.ts
  packages/platform-sdk-sol/src/services/identity/public-key.ts
  packages/platform-sdk/src/contracts/coins/identity.ts
Labels: Complexity: Medium, Status: Needs Review

#1164 refactor(crypto): separate BIP32 from BIP44
  packages/platform-sdk-btc/src/services/identity/utils.ts
  packages/platform-sdk-crypto/src/bip32.test.ts
  packages/platform-sdk-crypto/src/bip32.ts
  packages/platform-sdk-crypto/src/bip44.test.ts
  packages/platform-sdk-crypto/src/bip44.ts
  packages/platform-sdk-crypto/src/index.ts
  packages/platform-sdk-sol/src/services/identity/address.ts
Labels: Complexity: Low, Status: Needs Review

#1165 feat(sdk): implement ledger feature flags for transactions
  packages/platform-sdk/src/coins/network.models.ts
Labels: Complexity: Low, Status: Needs Review

#1166 feat(cli): implement message signing and verifying
  packages/platform-sdk-cli/src/commands/access-wallet.ts
  packages/platform-sdk-cli/src/commands/sign-message.ts
  packages/platform-sdk-cli/src/commands/verify-message.ts
Labels: Complexity: Medium, Status: Needs Review

#1167 refactor(btc-indexer): remove unnecessary database columns
  packages/platform-sdk-btc-indexer/src/database.ts
Labels: Complexity: Medium, Status: Needs Review

#1170 feat: implement `LedgerService#getExtendedPublicKey`
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/platform-sdk-ada/src/services/ledger.ts
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-ark/src/services/ledger.ts
  packages/platform-sdk-atom/src/services/ledger.ts
  packages/platform-sdk-avax/src/services/ledger.ts
  packages/platform-sdk-btc/src/services/ledger.ts
  packages/platform-sdk-dot/src/services/ledger.ts
  packages/platform-sdk-egld/src/services/ledger.ts
  packages/platform-sdk-eos/src/services/ledger.ts
  packages/platform-sdk-eth/src/services/ledger.ts
  packages/platform-sdk-lsk/src/services/ledger.ts
  packages/platform-sdk-neo/src/services/ledger.ts
  packages/platform-sdk-sol/src/services/ledger.ts
  packages/platform-sdk-trx/src/services/ledger.ts
  packages/platform-sdk-xlm/src/services/ledger.ts
  packages/platform-sdk-xrp/src/services/ledger.ts
  packages/platform-sdk/src/contracts/coins/ledger.ts
Labels: Complexity: Medium, Status: Needs Review

#1171 release: 3.1.0
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Status: Needs Review

#1173 fix(btc-server): remove trailing comma from migration
  packages/platform-sdk-btc-indexer/src/database.ts
Labels: Complexity: Low, Status: Needs Review

#1174 release: 3.1.1
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Status: Needs Review

#1175 feat(crypto): implement `HDKey` helper
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-crypto/src/hdkey.ts
Labels: Complexity: Low, Status: Needs Review

#1176 feat(crypto): implement `Base58` helper
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-crypto/src/base58.ts
Labels: Complexity: Low, Status: Needs Review

#1177 feat(crypto): implement more `BIP32` derivation methods
  jest.coverage.js
  packages/platform-sdk-crypto/src/bip32.ts
  packages/platform-sdk-crypto/src/bip44.ts
  packages/platform-sdk-crypto/src/index.ts
Labels: Complexity: Low, Status: Needs Review

#1178 chore: update network manifests
  packages/platform-sdk-ada/src/networks/ada/mainnet.ts
  packages/platform-sdk-ada/src/networks/ada/testnet.ts
  packages/platform-sdk-ark/src/networks/ark/devnet.ts
  packages/platform-sdk-ark/src/networks/ark/mainnet.ts
  packages/platform-sdk-ark/src/networks/compendia/mainnet.ts
  packages/platform-sdk-atom/src/networks/cosmos/mainnet.ts
  packages/platform-sdk-atom/src/networks/cosmos/testnet.ts
  packages/platform-sdk-avax/src/networks/avax/mainnet.ts
  packages/platform-sdk-avax/src/networks/avax/testnet.ts
  packages/platform-sdk-btc/src/networks/btc/livenet.ts
  packages/platform-sdk-btc/src/networks/btc/testnet.ts
  packages/platform-sdk-dot/src/networks/dot/mainnet.ts
  packages/platform-sdk-egld/src/networks/egld/mainnet.ts
  packages/platform-sdk-egld/src/networks/egld/testnet.ts
  packages/platform-sdk-eos/src/networks/bos/mainnet.ts
  packages/platform-sdk-eos/src/networks/eos/mainnet.ts
  packages/platform-sdk-eos/src/networks/eos/testnet.ts
  packages/platform-sdk-eos/src/networks/meetone/mainnet.ts
  packages/platform-sdk-eos/src/networks/telos/mainnet.ts
  packages/platform-sdk-eos/src/networks/telos/testnet.ts
  packages/platform-sdk-eos/src/networks/wax/mainnet.ts
  packages/platform-sdk-eos/src/networks/worbli/mainnet.ts
  packages/platform-sdk-eos/src/networks/worbli/testnet.ts
  packages/platform-sdk-eth/src/networks/eth/goerli.ts
  packages/platform-sdk-eth/src/networks/eth/kovan.ts
  packages/platform-sdk-eth/src/networks/eth/mainnet.ts
  packages/platform-sdk-eth/src/networks/eth/rinkeby.ts
  packages/platform-sdk-eth/src/networks/eth/ropsten.ts
  packages/platform-sdk-lsk/src/networks/lsk/mainnet.ts
  packages/platform-sdk-lsk/src/networks/lsk/testnet.ts
  packages/platform-sdk-neo/src/networks/neo/mainnet.ts
  packages/platform-sdk-neo/src/networks/neo/testnet.ts
  packages/platform-sdk-sol/src/networks/sol/mainnet.ts
  packages/platform-sdk-sol/src/networks/sol/testnet.ts
  packages/platform-sdk-trx/src/networks/trx/mainnet.ts
  packages/platform-sdk-trx/src/networks/trx/testnet.ts
  packages/platform-sdk-xlm/src/networks/xlm/mainnet.ts
  packages/platform-sdk-xlm/src/networks/xlm/testnet.ts
  packages/platform-sdk-xrp/src/networks/xrp/mainnet.ts
  packages/platform-sdk-xrp/src/networks/xrp/testnet.ts
  packages/platform-sdk/src/coins/network.models.ts
Labels: Complexity: Medium, Status: Needs Review

#1179 chore(profiles): add `ProfileSetting.DoNotShowAdvancedModeDisclaimer`
  packages/platform-sdk-profiles/src/profiles/profile.models.ts
  packages/platform-sdk-profiles/test/fixtures/network.json
Labels: Complexity: Low, Type: Task

#1180 feat(cli): implement IPFS
  packages/platform-sdk-cli/src/commands/access-wallet.ts
  packages/platform-sdk-cli/src/commands/index.ts
  packages/platform-sdk-cli/src/commands/send-ipfs.ts
  packages/platform-sdk-cli/src/commands/send-transaction.ts
Labels: Complexity: Medium, Status: Needs Review

#1181 feat(cli): implement multi-payment
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-cli/src/commands/helpers.ts
  packages/platform-sdk-cli/src/commands/import-ledger-wallet.ts
  packages/platform-sdk-cli/src/commands/send-delegate-registration.ts
  packages/platform-sdk-cli/src/commands/send-delegate-resignation.ts
  packages/platform-sdk-cli/src/commands/send-ipfs.ts
  packages/platform-sdk-cli/src/commands/send-multi-payment.ts
  packages/platform-sdk-cli/src/commands/send-second-signature-registration.ts
  packages/platform-sdk-cli/src/commands/send-vote.ts
  packages/platform-sdk-crypto/package.json
Labels: Complexity: Medium, Status: Needs Review

#1186 feat(profiles): implement bulk address import
  packages/platform-sdk-profiles/src/repositories/wallet-repository.ts
Labels: Complexity: Low, Status: Needs Review

#1187 feat(profiles): expose public key and private key import for wallets
  packages/platform-sdk-profiles/src/repositories/wallet-repository.ts
Labels: Complexity: Low, Status: Needs Review

#1188 release: 3.1.17
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Status: Needs Review

#1189 refactor(intl): append trailing zeros only if value is truthy
  packages/platform-sdk-intl/src/currency.test.ts
  packages/platform-sdk-intl/src/currency.ts
  packages/platform-sdk-profiles/src/repositories/wallet-repository.ts
Labels: Complexity: Low, Type: Refactor

#1190 release: 3.1.18
  CHANGELOG.md
  README.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
  scripts/publish.sh
Labels: Complexity: Medium, Type: Release

#1205 ci: set up `actions/labeler`
  .github/labeler.yml
  .github/workflows/labeler.yml
Labels: Complexity: Medium, Status: Needs Review

#1204 feat(crypto): implement `UUID` helper
  packages/platform-sdk-crypto/src/index.ts
  packages/platform-sdk-crypto/src/uuid.test.ts
  packages/platform-sdk-crypto/src/uuid.ts
Labels: Complexity: Medium, Status: Needs Review, domain/crypto

#1206 ci: update labeller configuration
  .github/labeler.yml
Labels: Complexity: Medium, Status: Needs Review

#1207 feat(profiles): implement WIF and encrypted WIF import
  packages/platform-sdk-profiles/src/repositories/wallet-repository.ts
  packages/platform-sdk-profiles/src/wallets/wallet.factory.test.ts
  packages/platform-sdk-profiles/src/wallets/wallet.factory.ts
Labels: Complexity: Medium, Domain: Profiles, Status: Needs Review

#1208 release: 3.1.20
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Domain: ADA, Domain: ARK, Domain: ATOM, Domain: AVAX, Domain: BTC, Domain: BTC/Indexer, Domain: BTC/Server, Domain: CLI, Domain: CoinCap, Domain: CoinGecko, Domain: Crypto, Domain: CryptoCompare, Domain: DOT, Domain: DOT/Indexer, Domain: EGLD, Domain: EOS, Domain: ETH, Domain: ETH/Indexer, Domain: ETH/Server, Domain: HTTP/axios, Domain: HTTP/bent, Domain: HTTP/got, Domain: HTTP/ky, Domain: HTTP/node-fetch, Domain: INTL, Domain: LSK, Domain: Markets, Domain: NEO, Domain: News, Domain: Profiles, Domain: SDK, Domain: SOL, Domain: Support, Domain: TRX, Domain: XLM, Domain: XRP, Type: Release

#1209 feat(crypto): implement `WIF` helpers
  packages/platform-sdk-crypto/src/index.ts
  packages/platform-sdk-crypto/src/wif.test.ts
  packages/platform-sdk-crypto/src/wif.ts
Labels: Complexity: Medium, Domain: Crypto, Status: Needs Review

#1212 feat: implement `LedgerService#scan`
  packages/platform-sdk-ada/src/services/ledger.ts
  packages/platform-sdk-ark/src/services/ledger.test.ts
  packages/platform-sdk-ark/src/services/ledger.ts
  packages/platform-sdk-ark/test/fixtures/client/wallet-2.json
  packages/platform-sdk-ark/test/fixtures/client/wallets-page-0.json
  packages/platform-sdk-ark/test/fixtures/client/wallets-page-1.json
  packages/platform-sdk-ark/test/fixtures/ledger.ts
  packages/platform-sdk-atom/src/services/ledger.ts
  packages/platform-sdk-avax/src/services/ledger.ts
  packages/platform-sdk-btc/src/services/ledger.ts
  packages/platform-sdk-crypto/src/wif.ts
  packages/platform-sdk-dot/src/services/ledger.ts
  packages/platform-sdk-egld/src/services/ledger.ts
  packages/platform-sdk-eos/src/services/ledger.ts
  packages/platform-sdk-eth/src/services/ledger.ts
  packages/platform-sdk-lsk/src/services/ledger.ts
  packages/platform-sdk-neo/src/services/ledger.ts
  packages/platform-sdk-profiles/src/wallets/wallet.factory.test.ts
  packages/platform-sdk-profiles/src/wallets/wallet.factory.ts
  packages/platform-sdk-sol/src/services/ledger.ts
  packages/platform-sdk-trx/src/services/ledger.ts
  packages/platform-sdk-xlm/src/services/ledger.ts
  packages/platform-sdk-xrp/src/services/ledger.ts
  packages/platform-sdk/src/contracts/coins/ledger.ts
Labels: Complexity: Medium, Domain: ADA, Domain: ARK, Domain: ATOM, Domain: AVAX, Domain: BTC, Domain: Crypto, Domain: DOT, Domain: EGLD, Domain: EOS, Domain: ETH, Domain: LSK, Domain: NEO, Domain: Profiles, Domain: SDK, Domain: SOL, Domain: TRX, Domain: XLM, Domain: XRP, Status: Needs Review, Type: Feature

#1193 docs(support): add TSDoc comments
  packages/platform-sdk-support/src/validator.ts
Labels: Complexity: Low, Status: Needs Review, domain/support

#1198 docs(news): add TSDoc comments
  packages/platform-sdk-news/src/blockfolio.ts
  packages/platform-sdk-news/src/feed.ts
  packages/platform-sdk-support/src/validator.ts
Labels: Complexity: Low, Domain: News, Domain: Support, Status: Needs Review, domain/news

#1214 fix(profiles): expose `ReadWriteWallet#wif` and `ReadWriteWallet#usesWIF` methods
  packages/platform-sdk-profiles/src/wallets/wallet.models.ts
Labels: Complexity: Low, Domain: Profiles, Type: Bugfix

#1213 feat(ark): implement BIP44 compliant ledger derivation
  packages/platform-sdk-ada/src/services/ledger.ts
  packages/platform-sdk-ark/src/services/ledger.test.ts
  packages/platform-sdk-ark/src/services/ledger.ts
  packages/platform-sdk-atom/src/services/ledger.ts
  packages/platform-sdk-avax/src/services/ledger.ts
  packages/platform-sdk-btc/src/services/ledger.ts
  packages/platform-sdk-dot/src/services/ledger.ts
  packages/platform-sdk-egld/src/services/ledger.ts
  packages/platform-sdk-eos/src/services/ledger.ts
  packages/platform-sdk-eth/src/services/ledger.ts
  packages/platform-sdk-lsk/src/services/ledger.ts
  packages/platform-sdk-neo/src/services/ledger.ts
  packages/platform-sdk-sol/src/services/ledger.ts
  packages/platform-sdk-trx/src/services/ledger.ts
  packages/platform-sdk-xlm/src/services/ledger.ts
  packages/platform-sdk-xrp/src/services/ledger.ts
Labels: Complexity: Low, Domain: ADA, Domain: ARK, Domain: ATOM, Domain: AVAX, Domain: BTC, Domain: DOT, Domain: EGLD, Domain: EOS, Domain: ETH, Domain: LSK, Domain: NEO, Domain: SOL, Domain: TRX, Domain: XLM, Domain: XRP, Status: Needs Review

#1215 release: 3.1.24
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Domain: ADA, Domain: ARK, Domain: ATOM, Domain: AVAX, Domain: BTC, Domain: BTC/Indexer, Domain: BTC/Server, Domain: CLI, Domain: CoinCap, Domain: CoinGecko, Domain: Crypto, Domain: CryptoCompare, Domain: DOT, Domain: DOT/Indexer, Domain: EGLD, Domain: EOS, Domain: ETH, Domain: ETH/Indexer, Domain: ETH/Server, Domain: HTTP/axios, Domain: HTTP/bent, Domain: HTTP/got, Domain: HTTP/ky, Domain: HTTP/node-fetch, Domain: INTL, Domain: LSK, Domain: Markets, Domain: NEO, Domain: News, Domain: Profiles, Domain: SDK, Domain: SOL, Domain: Support, Domain: TRX, Domain: XLM, Domain: XRP, Type: Release

#1216 refactor(profiles): remove `excludeWalletsWithoutName` export setting
  packages/platform-sdk-profiles/src/profiles/profile.models.ts
  packages/platform-sdk-profiles/src/profiles/profile.test.ts
  packages/platform-sdk-profiles/src/profiles/profile.ts
  packages/platform-sdk-profiles/src/repositories/profile-repository.test.ts
  packages/platform-sdk-profiles/src/repositories/wallet-repository.ts
Labels: Complexity: Low, Domain: Profiles, Type: Refactor

#1217 feat(json-rpc): initial implementation
  .github/labeler.yml
  .github/workflows/ci.yml
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/platform-sdk-http-axios/test/fixtures/feed.xml
  packages/platform-sdk-http-bent/test/fixtures/feed.xml
  packages/platform-sdk-http-got/test/fixtures/feed.xml
  packages/platform-sdk-http-ky/test/fixtures/feed.xml
  packages/platform-sdk-http-node-fetch/test/fixtures/feed.xml
  packages/platform-sdk-json-rpc/LICENSE
  packages/platform-sdk-json-rpc/README.md
  packages/platform-sdk-json-rpc/banner.png
  packages/platform-sdk-json-rpc/bin/meow.js
  packages/platform-sdk-json-rpc/bin/run
  packages/platform-sdk-json-rpc/bin/subscribe.js
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-json-rpc/src/helpers.ts
  packages/platform-sdk-json-rpc/src/index.ts
  packages/platform-sdk-json-rpc/src/methods/identity/address.ts
  packages/platform-sdk-json-rpc/src/methods/identity/keys.ts
  packages/platform-sdk-json-rpc/src/methods/identity/private-key.ts
  packages/platform-sdk-json-rpc/src/methods/identity/public-key.ts
  packages/platform-sdk-json-rpc/src/methods/identity/wif.ts
  packages/platform-sdk-json-rpc/tsconfig.json
  packages/platform-sdk-news/test/fixtures/feed.xml
  packages/platform-sdk/src/contracts/coins/identity.ts
  rush.json
Labels: Complexity: High, Domain: HTTP/axios, Domain: HTTP/bent, Domain: HTTP/got, Domain: HTTP/ky, Domain: HTTP/node-fetch, Domain: News, Domain: SDK, Status: Needs Review, ci

#1218 release: 3.2.0
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Domain: ADA, Domain: ARK, Domain: ATOM, Domain: AVAX, Domain: BTC, Domain: BTC/Indexer, Domain: BTC/Server, Domain: CLI, Domain: CoinCap, Domain: CoinGecko, Domain: Crypto, Domain: CryptoCompare, Domain: DOT, Domain: DOT/Indexer, Domain: EGLD, Domain: EOS, Domain: ETH, Domain: ETH/Indexer, Domain: ETH/Server, Domain: HTTP/axios, Domain: HTTP/bent, Domain: HTTP/got, Domain: HTTP/ky, Domain: HTTP/node-fetch, Domain: INTL, Domain: JSPN-RPC, Domain: LSK, Domain: Markets, Domain: NEO, Domain: News, Domain: Profiles, Domain: SDK, Domain: SOL, Domain: Support, Domain: TRX, Domain: XLM, Domain: XRP, Type: Release

#1192 docs(intl): add TSDoc comments
  packages/platform-sdk-intl/src/currency.ts
  packages/platform-sdk-intl/src/datetime.ts
  packages/platform-sdk-intl/src/money.ts
  packages/platform-sdk-intl/src/numeral.ts
Labels: Complexity: High, Domain: INTL, Status: Needs Review, domain/intl

#1199 docs(markets): add TSDoc comments
  packages/platform-sdk-markets/src/service.ts
Labels: Complexity: Medium, Domain: Markets, Status: Needs Review, domain/markets

#1219 feat(json-rpc): implement transfer signing and broadcasting
  packages/platform-sdk-coincap/src/index.ts
  packages/platform-sdk-json-rpc/src/index.ts
  packages/platform-sdk-json-rpc/src/methods/client.ts
  packages/platform-sdk-json-rpc/src/methods/identity/address.ts
  packages/platform-sdk-json-rpc/src/methods/identity/keys.ts
  packages/platform-sdk-json-rpc/src/methods/identity/private-key.ts
  packages/platform-sdk-json-rpc/src/methods/identity/public-key.ts
  packages/platform-sdk-json-rpc/src/methods/identity/wif.ts
  packages/platform-sdk-json-rpc/src/methods/transaction.ts
  packages/platform-sdk-markets/src/service.ts
Labels: Complexity: Medium, Status: Needs Review

#1220 feat(json-rpc): retrieve transaction, wallet and delegate details
  packages/platform-sdk-json-rpc/src/methods/client.ts
Labels: Complexity: Low, Status: Needs Review

#1223 release: 3.2.2
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Domain: ADA, Domain: ARK, Domain: ATOM, Domain: AVAX, Domain: BTC, Domain: BTC/Indexer, Domain: BTC/Server, Domain: CLI, Domain: CoinCap, Domain: CoinGecko, Domain: Crypto, Domain: CryptoCompare, Domain: DOT, Domain: DOT/Indexer, Domain: EGLD, Domain: EOS, Domain: ETH, Domain: ETH/Indexer, Domain: ETH/Server, Domain: HTTP/axios, Domain: HTTP/bent, Domain: HTTP/got, Domain: HTTP/ky, Domain: HTTP/node-fetch, Domain: INTL, Domain: JSPN-RPC, Domain: LSK, Domain: Markets, Domain: NEO, Domain: News, Domain: Profiles, Domain: SDK, Domain: SOL, Domain: Support, Domain: TRX, Domain: XLM, Domain: XRP, Type: Release

#1224 refactor(json-rpc): cache coin instance based on network
  packages/platform-sdk-json-rpc/src/helpers.ts
  packages/platform-sdk-json-rpc/src/index.ts
  packages/platform-sdk-json-rpc/src/methods/client.ts
  packages/platform-sdk-json-rpc/src/methods/identity/address.ts
  packages/platform-sdk-json-rpc/src/methods/identity/keys.ts
  packages/platform-sdk-json-rpc/src/methods/identity/private-key.ts
  packages/platform-sdk-json-rpc/src/methods/identity/public-key.ts
  packages/platform-sdk-json-rpc/src/methods/identity/wif.ts
  packages/platform-sdk-json-rpc/src/methods/transaction.ts
Labels: Complexity: Medium, Domain: JSPN-RPC, Status: Needs Review

#1225 feat(json-rpc): implement wallet generation
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-json-rpc/src/helpers.ts
  packages/platform-sdk-json-rpc/src/index.ts
  packages/platform-sdk-json-rpc/src/methods/client.ts
  packages/platform-sdk-json-rpc/src/methods/wallet.ts
Labels: Complexity: Low, Domain: JSPN-RPC, Status: Needs Review

#1194 docs(http): add TSDoc comments
  packages/platform-sdk-http-axios/src/request.ts
  packages/platform-sdk-http-bent/src/request.ts
  packages/platform-sdk-http-got/src/request.ts
  packages/platform-sdk-http-ky/src/request.ts
  packages/platform-sdk-http-node-fetch/src/request.ts
Labels: Complexity: Low, Domain: HTTP/axios, Domain: HTTP/bent, Domain: HTTP/got, Domain: HTTP/ky, Domain: HTTP/node-fetch, Status: Needs Review, domain/http/axios, domain/http/bent, domain/http/got, domain/http/ky, domain/http/node-fetch

#1202 docs(cryptocompare): add TSDoc comments
  packages/platform-sdk-cryptocompare/src/index.ts
  packages/platform-sdk-cryptocompare/src/transformers/historical-price-transformer.ts
  packages/platform-sdk-cryptocompare/src/transformers/historical-volume-transformer.ts
  packages/platform-sdk-cryptocompare/src/transformers/market-transformer.ts
Labels: Complexity: Medium, Domain: CryptoCompare, Status: Needs Review, domain/cryptocompare

#1200 docs(coincap): add TSDoc comments
  packages/platform-sdk-coincap/src/index.ts
  packages/platform-sdk-coincap/src/transformers/historical-price-transformer.ts
  packages/platform-sdk-coincap/src/transformers/market-transformer.ts
  packages/platform-sdk-coincap/src/utils.ts
Labels: Complexity: Medium, Domain: CoinCap, Status: Needs Review, domain/coincap

#1201 docs(coingecko): add TSDoc comments
  packages/platform-sdk-coingecko/src/index.ts
  packages/platform-sdk-coingecko/src/transformers/historical-price-transformer.ts
  packages/platform-sdk-coingecko/src/transformers/historical-volume-transformer.ts
  packages/platform-sdk-coingecko/src/transformers/market-transformer.ts
Labels: Complexity: Medium, Domain: CoinGecko, Status: Needs Review, domain/coingecko

#1226 fix(profiles): include bip38 data in `ReadWriteWallet#toObject`
  packages/platform-sdk-profiles/src/wallets/wallet.ts
Labels: Complexity: Low, Domain: Profiles, Status: Needs Review, Type: Bugfix

#1227 release: 3.2.5
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Domain: ADA, Domain: ARK, Domain: ATOM, Domain: AVAX, Domain: BTC, Domain: BTC/Indexer, Domain: BTC/Server, Domain: CLI, Domain: CoinCap, Domain: CoinGecko, Domain: Crypto, Domain: CryptoCompare, Domain: DOT, Domain: DOT/Indexer, Domain: EGLD, Domain: EOS, Domain: ETH, Domain: ETH/Indexer, Domain: ETH/Server, Domain: HTTP/axios, Domain: HTTP/bent, Domain: HTTP/got, Domain: HTTP/ky, Domain: HTTP/node-fetch, Domain: INTL, Domain: JSPN-RPC, Domain: LSK, Domain: Markets, Domain: NEO, Domain: News, Domain: Profiles, Domain: SDK, Domain: SOL, Domain: Support, Domain: TRX, Domain: XLM, Domain: XRP, Type: Release

#1228 feat(json-rpc): implement message service
  packages/platform-sdk-json-rpc/bin/run
  packages/platform-sdk-json-rpc/src/index.ts
  packages/platform-sdk-json-rpc/src/methods/message.ts
Labels: Complexity: Low, Domain: JSPN-RPC, Status: Needs Review

#1229 release: 3.2.6
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Domain: ADA, Domain: ARK, Domain: ATOM, Domain: AVAX, Domain: BTC, Domain: BTC/Indexer, Domain: BTC/Server, Domain: CLI, Domain: CoinCap, Domain: CoinGecko, Domain: Crypto, Domain: CryptoCompare, Domain: DOT, Domain: DOT/Indexer, Domain: EGLD, Domain: EOS, Domain: ETH, Domain: ETH/Indexer, Domain: ETH/Server, Domain: HTTP/axios, Domain: HTTP/bent, Domain: HTTP/got, Domain: HTTP/ky, Domain: HTTP/node-fetch, Domain: INTL, Domain: JSPN-RPC, Domain: LSK, Domain: Markets, Domain: NEO, Domain: News, Domain: Profiles, Domain: SDK, Domain: SOL, Domain: Support, Domain: TRX, Domain: XLM, Domain: XRP, Type: Release

#1230 perf(profiles): perform concurrent delegate synchronisation if possible
  packages/platform-sdk-ada/src/services/client.ts
  packages/platform-sdk-ark/src/networks/ark/devnet.ts
  packages/platform-sdk-ark/src/networks/ark/mainnet.ts
  packages/platform-sdk-ark/src/networks/compendia/mainnet.ts
  packages/platform-sdk-ark/src/services/client.ts
  packages/platform-sdk-atom/src/services/client.ts
  packages/platform-sdk-avax/src/services/client.ts
  packages/platform-sdk-egld/src/services/client.ts
  packages/platform-sdk-eth/src/services/client.ts
  packages/platform-sdk-json-rpc/src/methods/wallet.ts
  packages/platform-sdk-lsk/src/services/client.ts
  packages/platform-sdk-neo/src/services/client.ts
  packages/platform-sdk-profiles/src/dto/transaction-collection.test.ts
  packages/platform-sdk-profiles/src/dto/transaction-mapper.test.ts
  packages/platform-sdk-profiles/src/environment/env.test.ts
  packages/platform-sdk-profiles/src/environment/services/delegate-service.ts
  packages/platform-sdk-profiles/src/profiles/aggregates/transaction-aggregate.ts
  packages/platform-sdk-profiles/test/fixtures/network.json
  packages/platform-sdk-xlm/src/services/client.ts
  packages/platform-sdk-xrp/src/services/client.ts
  packages/platform-sdk/src/coins/collections/paginator.test.ts
  packages/platform-sdk/src/coins/collections/paginator.ts
  packages/platform-sdk/src/coins/enums.test.ts
  packages/platform-sdk/src/coins/enums.ts
  packages/platform-sdk/src/coins/network-repository.test.ts
  packages/platform-sdk/src/coins/network.models.ts
  packages/platform-sdk/src/coins/network.test.ts
  packages/platform-sdk/src/contracts/coins/client.ts
  packages/platform-sdk/src/helpers.test.ts
Labels: Complexity: Medium, Domain: ADA, Domain: ARK, Domain: ATOM, Domain: AVAX, Domain: EGLD, Domain: ETH, Domain: JSPN-RPC, Domain: LSK, Domain: NEO, Domain: Profiles, Domain: SDK, Domain: XLM, Domain: XRP, Status: Needs Review

#1231 release: 3.2.7
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Type: Release

#1195 docs(btc-indexer): add TSDoc comments
  packages/platform-sdk-btc-indexer/src/client.ts
  packages/platform-sdk-btc-indexer/src/database.ts
  packages/platform-sdk-btc-indexer/src/helpers.ts
  packages/platform-sdk-btc-indexer/src/index.ts
  packages/platform-sdk-btc-indexer/src/types.ts
Labels: Complexity: Medium, Domain: BTC/Indexer, Status: Needs Review, domain/btc/indexer

#1232 feat(profiles): implement storage that uses system configuration path
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-profiles/src/environment/storage/conf.test.ts
  packages/platform-sdk-profiles/src/environment/storage/conf.ts
  packages/platform-sdk-profiles/src/environment/storage/factory.ts
Labels: Complexity: Medium, Domain: Profiles, Status: Needs Review

#1234 refactor(profiles): extract environment configuration into drivers
  packages/platform-sdk-profiles/src/drivers/contracts.ts
  packages/platform-sdk-profiles/src/drivers/driver.factory.ts
  packages/platform-sdk-profiles/src/drivers/memory/index.ts
  packages/platform-sdk-profiles/src/environment/container.helpers.ts
  packages/platform-sdk-profiles/src/environment/env.models.ts
  packages/platform-sdk-profiles/src/environment/env.test.ts
  packages/platform-sdk-profiles/src/environment/env.ts
Labels: Complexity: High, Domain: Profiles, Status: Needs Review

#1235 refactor(profiles): extract implementation contracts
  packages/platform-sdk-profiles/src/drivers/contracts/contacts/contact-address.ts
  packages/platform-sdk-profiles/src/drivers/contracts/contacts/contact.ts
  packages/platform-sdk-profiles/src/drivers/contracts/mappers/delegate-mapper.ts
  packages/platform-sdk-profiles/src/drivers/contracts/plugins/plugin-registry.ts
  packages/platform-sdk-profiles/src/drivers/contracts/plugins/plugin-repository.ts
  packages/platform-sdk-profiles/src/drivers/contracts/profiles/aggregates/count-aggregate.ts
  packages/platform-sdk-profiles/src/drivers/contracts/profiles/aggregates/registration-aggregate.ts
  packages/platform-sdk-profiles/src/drivers/contracts/profiles/aggregates/transaction-aggregate.ts
  packages/platform-sdk-profiles/src/drivers/contracts/profiles/aggregates/wallet-aggregate.ts
  packages/platform-sdk-profiles/src/drivers/contracts/profiles/authenticator.ts
  packages/platform-sdk-profiles/src/drivers/contracts/profiles/migrator.ts
  packages/platform-sdk-profiles/src/drivers/contracts/profiles/profile.factory.ts
  packages/platform-sdk-profiles/src/drivers/contracts/profiles/profile.ts
  packages/platform-sdk-profiles/src/drivers/contracts/repositories/contact-address-repository.ts
  packages/platform-sdk-profiles/src/drivers/contracts/repositories/contact-repository.ts
  packages/platform-sdk-profiles/src/drivers/contracts/repositories/data-repository.ts
  packages/platform-sdk-profiles/src/drivers/contracts/repositories/notification-repository.ts
  packages/platform-sdk-profiles/src/drivers/contracts/repositories/peer-repository.ts
  packages/platform-sdk-profiles/src/drivers/contracts/repositories/profile-repository.ts
  packages/platform-sdk-profiles/src/drivers/contracts/repositories/setting-repository.ts
  packages/platform-sdk-profiles/src/drivers/contracts/repositories/wallet-repository.ts
  packages/platform-sdk-profiles/src/drivers/contracts/services/avatar.ts
  packages/platform-sdk-profiles/src/drivers/contracts/services/cache.ts
  packages/platform-sdk-profiles/src/drivers/contracts/services/coin-service.ts
  packages/platform-sdk-profiles/src/drivers/contracts/services/delegate-service.ts
  packages/platform-sdk-profiles/src/drivers/contracts/services/exchange-rate-service.ts
  packages/platform-sdk-profiles/src/drivers/contracts/services/fee-service.ts
  packages/platform-sdk-profiles/src/drivers/contracts/services/known-wallet-service.ts
  packages/platform-sdk-profiles/src/drivers/contracts/services/wallet-service.ts
  packages/platform-sdk-profiles/src/drivers/contracts/wallets/read-only-wallet.ts
  packages/platform-sdk-profiles/src/drivers/contracts/wallets/wallet-transaction-service.ts
  packages/platform-sdk-profiles/src/drivers/contracts/wallets/wallet.factory.ts
  packages/platform-sdk-profiles/src/drivers/contracts/wallets/wallet.ts
Labels: Complexity: Undetermined, Domain: Profiles, Status: Needs Review

#1236 refactor(profiles): move `DTO` namespace into the root
  packages/platform-sdk-profiles/src/drivers/contracts/profiles/aggregates/transaction-aggregate.ts
  packages/platform-sdk-profiles/src/drivers/contracts/wallets/wallet.ts
  packages/platform-sdk-profiles/src/drivers/memory/profiles/aggregates/transaction-aggregate.ts
  packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.models.ts
  packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.ts
  packages/platform-sdk-profiles/src/dto/transaction-collection.test.ts
  packages/platform-sdk-profiles/src/dto/transaction-collection.ts
  packages/platform-sdk-profiles/src/dto/transaction-mapper.test.ts
  packages/platform-sdk-profiles/src/dto/transaction-mapper.ts
  packages/platform-sdk-profiles/src/dto/transaction.test.ts
  packages/platform-sdk-profiles/src/dto/transaction.ts
  packages/platform-sdk-profiles/src/index.ts
Labels: Complexity: Low, Status: Needs Review

#1237 refactor(profiles): temporarily prefix all contracts with `I`
  packages/platform-sdk-profiles/src/drivers/contracts/mappers/delegate-mapper.ts
  packages/platform-sdk-profiles/src/drivers/contracts/plugins/plugin-registry.ts
  packages/platform-sdk-profiles/src/drivers/contracts/plugins/plugin-repository.ts
  packages/platform-sdk-profiles/src/drivers/contracts/profiles/aggregates/registration-aggregate.ts
  packages/platform-sdk-profiles/src/drivers/contracts/profiles/aggregates/transaction-aggregate.ts
  packages/platform-sdk-profiles/src/drivers/contracts/profiles/profile.enum.ts
  packages/platform-sdk-profiles/src/drivers/contracts/profiles/profile.ts
  packages/platform-sdk-profiles/src/drivers/contracts/repositories/notification-repository.ts
  packages/platform-sdk-profiles/src/drivers/contracts/repositories/peer-repository.ts
  packages/platform-sdk-profiles/src/drivers/contracts/repositories/wallet-repository.ts
  packages/platform-sdk-profiles/src/drivers/contracts/services/known-wallet-service.ts
  packages/platform-sdk-profiles/src/drivers/contracts/wallets/wallet.enum.ts
  packages/platform-sdk-profiles/src/drivers/contracts/wallets/wallet.factory.ts
  packages/platform-sdk-profiles/src/drivers/contracts/wallets/wallet.ts
Labels: Complexity: High, Status: Needs Review

#1240 fix(ark): handle different broadcast response error types
  packages/platform-sdk-ark/src/services/client.ts
Labels: Complexity: Low, Domain: ARK, Type: Bugfix

#1241 release: 4.0.0
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Domain: ADA, Domain: ARK, Domain: ATOM, Domain: AVAX, Domain: BTC, Domain: BTC/Indexer, Domain: BTC/Server, Domain: CLI, Domain: CoinCap, Domain: CoinGecko, Domain: Crypto, Domain: CryptoCompare, Domain: DOT, Domain: DOT/Indexer, Domain: EGLD, Domain: EOS, Domain: ETH, Domain: ETH/Indexer, Domain: ETH/Server, Domain: HTTP/axios, Domain: HTTP/bent, Domain: HTTP/got, Domain: HTTP/ky, Domain: HTTP/node-fetch, Domain: INTL, Domain: JSPN-RPC, Domain: LSK, Domain: Markets, Domain: NEO, Domain: News, Domain: Profiles, Domain: SDK, Domain: SOL, Domain: Support, Domain: TRX, Domain: XLM, Domain: XRP, Type: Release

#1242 fix(profiles): export `Avatar` helper
  packages/platform-sdk-profiles/src/contracts/services/avatar.ts
  packages/platform-sdk-profiles/src/contracts/services/index.ts
  packages/platform-sdk-profiles/src/drivers/memory/contacts/contact-address.ts
  packages/platform-sdk-profiles/src/drivers/memory/contacts/contact.ts
  packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.ts
  packages/platform-sdk-profiles/src/drivers/memory/wallets/read-only-wallet.ts
  packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.ts
  packages/platform-sdk-profiles/src/helpers/__snapshots__/avatar.test.ts.snap
  packages/platform-sdk-profiles/src/helpers/avatar.test.ts
  packages/platform-sdk-profiles/src/helpers/avatar.ts
  packages/platform-sdk-profiles/src/helpers/index.ts
Labels: Complexity: Low, Domain: Profiles, Status: Needs Review

#1243 release: 4.0.1
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Type: Release

#1245 refactor(profiles): expose externally used classes
  packages/platform-sdk-profiles/src/contracts/services/delegate-service.ts
  packages/platform-sdk-profiles/src/contracts/wallets/wallet.ts
  packages/platform-sdk-profiles/src/drivers/memory/index.ts
  packages/platform-sdk-profiles/src/drivers/memory/mappers/delegate-mapper.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/mappers/delegate-mapper.ts
  packages/platform-sdk-profiles/src/drivers/memory/plugins/plugin-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/contact-address-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/contact-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/notification-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/peer-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/profile-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/setting-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/wallet-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/services/coin-service.ts
  packages/platform-sdk-profiles/src/drivers/memory/services/delegate-service.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/services/delegate-service.ts
  packages/platform-sdk-profiles/src/drivers/memory/services/exchange-rate-service.ts
  packages/platform-sdk-profiles/src/drivers/memory/services/fee-service.ts
  packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet-transaction-service.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.ts
  packages/platform-sdk-profiles/src/dto/transaction-mapper.test.ts
  packages/platform-sdk-profiles/src/environment/container.models.ts
  packages/platform-sdk-profiles/src/environment/env.test.ts
  packages/platform-sdk-profiles/src/environment/env.ts
  packages/platform-sdk-profiles/src/index.ts
  packages/platform-sdk-profiles/src/repositories/data-repository.test.ts
  packages/platform-sdk-profiles/src/repositories/data-repository.ts
  packages/platform-sdk-profiles/src/repositories/index.ts
  packages/platform-sdk-profiles/test/helpers.ts
  packages/platform-sdk-support/src/index.ts
Labels: Complexity: Low, Domain: Profiles, Domain: Support, Status: Needs Review

#1246 release: 4.0.2
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Type: Release

#1244 feat(ark): sign message with wif
  packages/platform-sdk-ada/src/services/message.ts
  packages/platform-sdk-ark/src/services/message.test.ts
  packages/platform-sdk-ark/src/services/message.ts
  packages/platform-sdk-atom/src/services/message.ts
  packages/platform-sdk-avax/src/services/message.ts
  packages/platform-sdk-btc/src/services/message.ts
  packages/platform-sdk-dot/src/services/message.ts
  packages/platform-sdk-eos/src/services/message.ts
  packages/platform-sdk-lsk/src/services/message.ts
  packages/platform-sdk-neo/src/services/message.ts
  packages/platform-sdk-profiles/src/environment/env.test.ts
  packages/platform-sdk-profiles/src/repositories/data-repository.ts
  packages/platform-sdk-xlm/src/services/message.ts
  packages/platform-sdk-xrp/src/services/message.ts
  packages/platform-sdk/src/contracts/coins/message.ts
Labels: Complexity: Low, Domain: ADA, Domain: ARK, Domain: ATOM, Domain: AVAX, Domain: BTC, Domain: DOT, Domain: EOS, Domain: LSK, Domain: NEO, Domain: Profiles, Domain: SDK, Domain: XLM, Domain: XRP, Type: Feature

#1247 feat(rpc): implement transaction listing
  packages/platform-sdk-ark/src/services/message.test.ts
  packages/platform-sdk-json-rpc/src/methods/client.ts
Labels: Complexity: Low, Domain: ARK, Domain: JSPN-RPC, Status: Needs Review

#1248 release: 4.0.4
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Type: Release

#1251 refactor(profiles): lazily construct driver instances
  packages/platform-sdk-profiles/src/drivers/driver.factory.ts
  packages/platform-sdk-profiles/src/environment/storage/factory.ts
Labels: Complexity: Low, Domain: Profiles, Status: Needs Review

#1252 release: 4.0.5
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Domain: ADA, Domain: ARK, Domain: ATOM, Domain: AVAX, Domain: BTC, Domain: BTC/Indexer, Domain: BTC/Server, Domain: CLI, Domain: CoinCap, Domain: CoinGecko, Domain: Crypto, Domain: CryptoCompare, Domain: DOT, Domain: DOT/Indexer, Domain: EGLD, Domain: EOS, Domain: ETH, Domain: ETH/Indexer, Domain: ETH/Server, Domain: HTTP/axios, Domain: HTTP/bent, Domain: HTTP/got, Domain: HTTP/ky, Domain: HTTP/node-fetch, Domain: INTL, Domain: JSPN-RPC, Domain: LSK, Domain: Markets, Domain: NEO, Domain: News, Domain: Profiles, Domain: SDK, Domain: SOL, Domain: Support, Domain: TRX, Domain: XLM, Domain: XRP, Type: Release

#1258 fix(profiles): only use custom peer if setting is enabled
  packages/platform-sdk-profiles/src/contracts/profiles/profile.ts
  packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.ts
  packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.ts
Labels: Complexity: Low, Domain: Profiles, Status: Needs Review

#1259 refactor(profiles): use correct peer, plugin and notification interfaces
  packages/platform-sdk-profiles/src/contracts/plugins/plugin-repository.ts
  packages/platform-sdk-profiles/src/contracts/repositories/notification-repository.ts
  packages/platform-sdk-profiles/src/contracts/repositories/peer-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/plugins/plugin-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/notification-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/peer-repository.ts
Labels: Complexity: Medium, Status: Needs Review

#1239 refactor(profiles): use `inversify` as DI container
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  jest.coverage.js
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-profiles/src/drivers/memory/contacts/contact-address.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/contacts/contact.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/index.ts
  packages/platform-sdk-profiles/src/drivers/memory/plugins/plugin-registry.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/plugins/plugin-repository.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/profiles/aggregates/count-aggregate.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/profiles/aggregates/registration-aggregate.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/profiles/aggregates/transaction-aggregate.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/profiles/aggregates/wallet-aggregate.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/profiles/authenticator.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/profiles/migrator.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/contact-address-repository.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/contact-address-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/contact-repository.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/contact-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/notification-repository.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/notification-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/peer-repository.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/peer-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/profile-repository.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/profile-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/setting-repository.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/setting-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/wallet-repository.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/wallet-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/services/coin-service.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/services/coin-service.ts
  packages/platform-sdk-profiles/src/drivers/memory/services/delegate-service.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/services/delegate-service.ts
  packages/platform-sdk-profiles/src/drivers/memory/services/exchange-rate-service.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/services/exchange-rate-service.ts
  packages/platform-sdk-profiles/src/drivers/memory/services/fee-service.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/services/fee-service.ts
  packages/platform-sdk-profiles/src/drivers/memory/services/known-wallet-service.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/services/known-wallet-service.ts
  packages/platform-sdk-profiles/src/drivers/memory/services/wallet-service.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/services/wallet-service.ts
  packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet-transaction-service.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.factory.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.test.ts
  packages/platform-sdk-profiles/src/dto/transaction-mapper.test.ts
  packages/platform-sdk-profiles/src/dto/transaction.test.ts
  packages/platform-sdk-profiles/src/environment/container.test.ts
  packages/platform-sdk-profiles/src/environment/container.ts
  packages/platform-sdk-profiles/src/environment/env.test.ts
  packages/platform-sdk-profiles/src/environment/env.ts
  packages/platform-sdk-profiles/src/helpers/password.test.ts
  packages/platform-sdk-profiles/src/index.ts
  packages/platform-sdk-profiles/src/repositories/data-repository.test.ts
  packages/platform-sdk-profiles/src/repositories/data-repository.ts
Labels: Complexity: Medium, Domain: Profiles, Status: Needs Review

#1256 refactor(profiles): split profile restoration into separate methods
  packages/platform-sdk-profiles/src/contracts/profiles/profile.ts
  packages/platform-sdk-profiles/src/contracts/repositories/contact-repository.ts
  packages/platform-sdk-profiles/src/contracts/repositories/wallet-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/contact-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/profile-repository.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/wallet-repository.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/wallet-repository.ts
  packages/platform-sdk-profiles/src/environment/env.test.ts
Labels: Complexity: Low, Domain: Profiles, Status: Needs Review

#1260 release: 4.1.0
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Domain: ADA, Domain: ARK, Domain: ATOM, Domain: AVAX, Domain: BTC, Domain: BTC/Indexer, Domain: BTC/Server, Domain: CLI, Domain: CoinCap, Domain: CoinGecko, Domain: Crypto, Domain: CryptoCompare, Domain: DOT, Domain: DOT/Indexer, Domain: EGLD, Domain: EOS, Domain: ETH, Domain: ETH/Indexer, Domain: ETH/Server, Domain: HTTP/axios, Domain: HTTP/bent, Domain: HTTP/got, Domain: HTTP/ky, Domain: HTTP/node-fetch, Domain: INTL, Domain: JSPN-RPC, Domain: LSK, Domain: Markets, Domain: NEO, Domain: News, Domain: Profiles, Domain: SDK, Domain: SOL, Domain: Support, Domain: TRX, Domain: XLM, Domain: XRP, Type: Release

#1261 feat(terra): initial draft implementation
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/platform-sdk-terra/LICENSE
  packages/platform-sdk-terra/README.md
  packages/platform-sdk-terra/banner.png
  packages/platform-sdk-terra/package.json
  packages/platform-sdk-terra/src/dto/index.ts
  packages/platform-sdk-terra/src/dto/signed-transaction.ts
  packages/platform-sdk-terra/src/dto/transaction.ts
  packages/platform-sdk-terra/src/dto/wallet.ts
  packages/platform-sdk-terra/src/index.ts
  packages/platform-sdk-terra/src/manifest.ts
  packages/platform-sdk-terra/src/networks/terra/mainnet.ts
  packages/platform-sdk-terra/src/networks/terra/testnet.ts
  packages/platform-sdk-terra/src/schema.ts
  packages/platform-sdk-terra/src/service-provider.ts
  packages/platform-sdk-terra/src/services/client.ts
  packages/platform-sdk-terra/src/services/data-transfer-object.ts
  packages/platform-sdk-terra/src/services/fee.ts
  packages/platform-sdk-terra/src/services/helpers.ts
  packages/platform-sdk-terra/src/services/identity/address-list.ts
  packages/platform-sdk-terra/src/services/identity/address.ts
  packages/platform-sdk-terra/src/services/identity/helpers.ts
  packages/platform-sdk-terra/src/services/identity/index.ts
  packages/platform-sdk-terra/src/services/identity/keys.ts
  packages/platform-sdk-terra/src/services/identity/private-key.ts
  packages/platform-sdk-terra/src/services/identity/public-key.ts
  packages/platform-sdk-terra/src/services/identity/wif.ts
  packages/platform-sdk-terra/src/services/index.ts
  packages/platform-sdk-terra/src/services/known-wallets.ts
  packages/platform-sdk-terra/src/services/ledger.ts
  packages/platform-sdk-terra/src/services/link.ts
  packages/platform-sdk-terra/src/services/message.ts
  packages/platform-sdk-terra/src/services/multi-signature.ts
  packages/platform-sdk-terra/src/services/peer.ts
  packages/platform-sdk-terra/src/services/transaction.ts
  packages/platform-sdk-terra/test/fixtures/client/transaction.json
  packages/platform-sdk-terra/test/fixtures/client/transactions-0.json
  packages/platform-sdk-terra/test/fixtures/client/transactions-20.json
  packages/platform-sdk-terra/test/fixtures/client/transactions.json
  packages/platform-sdk-terra/test/fixtures/client/utxos-aggregate.json
  packages/platform-sdk-terra/test/fixtures/client/wallet.json
  packages/platform-sdk-terra/test/fixtures/identity.ts
  packages/platform-sdk-terra/test/fixtures/transaction/expiration.json
  packages/platform-sdk-terra/test/fixtures/transaction/utxos.json
  packages/platform-sdk-terra/test/helpers.ts
  packages/platform-sdk-terra/test/mariano.test.ts
  packages/platform-sdk-terra/tsconfig.json
  packages/platform-sdk/src/coins/config.test.ts
  packages/platform-sdk/src/coins/config.ts
  rush.json
Labels: Complexity: Undetermined, Domain: SDK, Status: Needs Review

#1264 fix(profiles): make `PluginRegistry` an `injectable`
  packages/platform-sdk-profiles/src/drivers/memory/plugins/plugin-registry.ts
Labels: Complexity: Low, Status: Needs Review

#1265 chore: rename `terra` to `luna`
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/platform-sdk-luna/LICENSE
  packages/platform-sdk-luna/README.md
  packages/platform-sdk-luna/banner.png
  packages/platform-sdk-luna/package.json
  packages/platform-sdk-luna/src/dto/index.ts
  packages/platform-sdk-luna/src/dto/signed-transaction.ts
  packages/platform-sdk-luna/src/dto/transaction.ts
  packages/platform-sdk-luna/src/dto/wallet.ts
  packages/platform-sdk-luna/src/index.ts
  packages/platform-sdk-luna/src/manifest.ts
  packages/platform-sdk-luna/src/networks/luna/mainnet.ts
  packages/platform-sdk-luna/src/networks/luna/testnet.ts
  packages/platform-sdk-luna/src/schema.ts
  packages/platform-sdk-luna/src/service-provider.ts
  packages/platform-sdk-luna/src/services/client.ts
  packages/platform-sdk-luna/src/services/data-transfer-object.ts
  packages/platform-sdk-luna/src/services/fee.ts
  packages/platform-sdk-luna/src/services/helpers.ts
  packages/platform-sdk-luna/src/services/identity/address-list.ts
  packages/platform-sdk-luna/src/services/identity/address.ts
  packages/platform-sdk-luna/src/services/identity/helpers.ts
  packages/platform-sdk-luna/src/services/identity/index.ts
  packages/platform-sdk-luna/src/services/identity/keys.ts
  packages/platform-sdk-luna/src/services/identity/private-key.ts
  packages/platform-sdk-luna/src/services/identity/public-key.ts
  packages/platform-sdk-luna/src/services/identity/wif.ts
  packages/platform-sdk-luna/src/services/index.ts
  packages/platform-sdk-luna/src/services/known-wallets.ts
  packages/platform-sdk-luna/src/services/ledger.ts
  packages/platform-sdk-luna/src/services/link.ts
  packages/platform-sdk-luna/src/services/message.ts
  packages/platform-sdk-luna/src/services/multi-signature.ts
  packages/platform-sdk-luna/src/services/peer.ts
  packages/platform-sdk-luna/src/services/transaction.ts
  packages/platform-sdk-luna/test/fixtures/identity.ts
  packages/platform-sdk-luna/test/helpers.ts
  packages/platform-sdk-luna/tsconfig.json
  packages/platform-sdk-terra/src/manifest.ts
  rush.json
Labels: Complexity: Medium, Status: Needs Review

#1266 release: 4.1.3
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-luna/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-nano/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Type: Release

#1267 style: resolve style guide violations
  packages/platform-sdk-nano/package.json
  packages/platform-sdk-nano/src/services/client.ts
  packages/platform-sdk-nano/src/services/identity/address.ts
  packages/platform-sdk-nano/src/services/identity/helpers.ts
  packages/platform-sdk-nano/src/services/transaction.ts
Labels: Complexity: Low, Status: Needs Review

#1268 refactor(profiles): make last known network configuration available before wallet sync
  packages/platform-sdk-profiles/src/contracts/wallets/wallet.ts
  packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/profiles/profile.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/profile-repository.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/repositories/wallet-repository.ts
  packages/platform-sdk-profiles/src/drivers/memory/wallets/__snapshots__/wallet.test.ts.snap
  packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.ts
  packages/platform-sdk-profiles/src/environment/env.test.ts
  packages/platform-sdk-profiles/test/fixtures/env-storage.json
Labels: Complexity: Low, Domain: Profiles, Status: Needs Review

#1269 release: 4.1.4
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-luna/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-nano/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Domain: ADA, Domain: ARK, Domain: ATOM, Domain: AVAX, Domain: BTC, Domain: BTC/Indexer, Domain: BTC/Server, Domain: CLI, Domain: CoinCap, Domain: CoinGecko, Domain: Crypto, Domain: CryptoCompare, Domain: DOT, Domain: DOT/Indexer, Domain: EGLD, Domain: EOS, Domain: ETH, Domain: ETH/Indexer, Domain: ETH/Server, Domain: HTTP/axios, Domain: HTTP/bent, Domain: HTTP/got, Domain: HTTP/ky, Domain: HTTP/node-fetch, Domain: INTL, Domain: JSPN-RPC, Domain: LSK, Domain: Markets, Domain: NEO, Domain: News, Domain: Profiles, Domain: SDK, Domain: SOL, Domain: Support, Domain: TRX, Domain: XLM, Domain: XRP, Type: Release

#1270 release: 4.1.5
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-luna/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-nano/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Type: Release

#1273 release: 4.1.6
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc-server/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-cli/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-luna/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-nano/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-sol/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Domain: ADA, Domain: ARK, Domain: ATOM, Domain: AVAX, Domain: BTC, Domain: BTC/Indexer, Domain: BTC/Server, Domain: CLI, Domain: CoinCap, Domain: CoinGecko, Domain: Crypto, Domain: CryptoCompare, Domain: DOT, Domain: DOT/Indexer, Domain: EGLD, Domain: EOS, Domain: ETH, Domain: ETH/Indexer, Domain: ETH/Server, Domain: HTTP/axios, Domain: HTTP/bent, Domain: HTTP/got, Domain: HTTP/ky, Domain: HTTP/node-fetch, Domain: INTL, Domain: JSPN-RPC, Domain: LSK, Domain: Markets, Domain: NEO, Domain: News, Domain: Profiles, Domain: SDK, Domain: SOL, Domain: Support, Domain: TRX, Domain: XLM, Domain: XRP, Type: Release

#1274 refactor(profiles): implement `ReadWriteWallet#setWif`
  packages/platform-sdk-profiles/src/contracts/wallets/wallet.ts
  packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.test.ts
  packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.ts
Labels: Complexity: Low, Domain: Profiles, Type: Refactor

#1275 refactor(avax): compute transaction ID as sha256 hash
  packages/platform-sdk-avax/src/services/transaction.ts
Labels: Complexity: Low, Domain: AVAX, Status: Needs Review

#1271 refactor: implement `Network#expirationType`
  packages/platform-sdk-ada/src/networks/ada/mainnet.ts
  packages/platform-sdk-ada/src/networks/ada/testnet.ts
  packages/platform-sdk-ark/src/networks/ark/devnet.ts
  packages/platform-sdk-ark/src/networks/ark/mainnet.ts
  packages/platform-sdk-ark/src/networks/compendia/mainnet.ts
  packages/platform-sdk-atom/src/networks/cosmos/mainnet.ts
  packages/platform-sdk-atom/src/networks/cosmos/testnet.ts
  packages/platform-sdk-atom/src/networks/terra/mainnet.ts
  packages/platform-sdk-atom/src/networks/terra/testnet.ts
  packages/platform-sdk-avax/src/networks/avax/mainnet.ts
  packages/platform-sdk-avax/src/networks/avax/testnet.ts
  packages/platform-sdk-btc/src/networks/btc/livenet.ts
  packages/platform-sdk-btc/src/networks/btc/testnet.ts
  packages/platform-sdk-dot/src/networks/dot/mainnet.ts
  packages/platform-sdk-egld/src/networks/egld/mainnet.ts
  packages/platform-sdk-egld/src/networks/egld/testnet.ts
  packages/platform-sdk-eos/src/networks/bos/mainnet.ts
  packages/platform-sdk-eos/src/networks/eos/mainnet.ts
  packages/platform-sdk-eos/src/networks/eos/testnet.ts
  packages/platform-sdk-eos/src/networks/meetone/mainnet.ts
  packages/platform-sdk-eos/src/networks/telos/mainnet.ts
  packages/platform-sdk-eos/src/networks/telos/testnet.ts
  packages/platform-sdk-eos/src/networks/wax/mainnet.ts
  packages/platform-sdk-eos/src/networks/worbli/mainnet.ts
  packages/platform-sdk-eos/src/networks/worbli/testnet.ts
  packages/platform-sdk-eth/src/networks/eth/goerli.ts
  packages/platform-sdk-eth/src/networks/eth/kovan.ts
  packages/platform-sdk-eth/src/networks/eth/mainnet.ts
  packages/platform-sdk-eth/src/networks/eth/rinkeby.ts
  packages/platform-sdk-eth/src/networks/eth/ropsten.ts
  packages/platform-sdk-lsk/src/networks/lsk/mainnet.ts
  packages/platform-sdk-lsk/src/networks/lsk/testnet.ts
  packages/platform-sdk-luna/src/networks/luna/mainnet.ts
  packages/platform-sdk-luna/src/networks/luna/testnet.ts
  packages/platform-sdk-nano/src/networks/nano/mainnet.ts
  packages/platform-sdk-nano/src/networks/nano/testnet.ts
  packages/platform-sdk-neo/src/networks/neo/mainnet.ts
  packages/platform-sdk-neo/src/networks/neo/testnet.ts
  packages/platform-sdk-profiles/test/fixtures/network.json
  packages/platform-sdk-sol/src/networks/sol/mainnet.ts
  packages/platform-sdk-sol/src/networks/sol/testnet.ts
  packages/platform-sdk-trx/src/networks/trx/mainnet.ts
  packages/platform-sdk-trx/src/networks/trx/testnet.ts
  packages/platform-sdk-xlm/src/networks/xlm/mainnet.ts
  packages/platform-sdk-xlm/src/networks/xlm/testnet.ts
  packages/platform-sdk-xrp/src/networks/xrp/mainnet.ts
  packages/platform-sdk-xrp/src/networks/xrp/testnet.ts
  packages/platform-sdk/src/coins/network-repository.test.ts
  packages/platform-sdk/src/coins/network.models.ts
  packages/platform-sdk/src/coins/network.test.ts
  packages/platform-sdk/src/coins/network.ts
Labels: Complexity: Low, Domain: ADA, Domain: ARK, Domain: ATOM, Domain: AVAX, Domain: BTC, Domain: DOT, Domain: EGLD, Domain: EOS, Domain: ETH, Domain: LSK, Domain: NEO, Domain: Profiles, Domain: SDK, Domain: SOL, Domain: TRX, Domain: XLM, Domain: XRP, Status: Needs Review, Type: Refactor

#1277 fix: allow multiple addresses in profile transactions aggregate
  packages/platform-sdk-profiles/src/drivers/memory/wallets/wallet.ts
Labels: Domain: Profiles
