Repository ArkEcosystem/platform-sdk, pull requests merged in 2021-02, with the labels that each got.

#1061 chore(crypto): update `string-crypto` dependency
  .pnp.js
  .yarn/cache/pbkdf2-npm-3.1.1-bd4801f9ae-2.zip
  .yarn/cache/string-crypto-npm-1.0.4-dda784909f-2.zip
  .yarn/cache/string-crypto-npm-2.0.1-0dcc2d61e9-2.zip
  .yarn/install-state.gz
  packages/platform-sdk-crypto/package.json
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review

#1064 feat(profiles): add `ProfileSetting.ErrorReporting`
  packages/platform-sdk-profiles/src/profiles/profile.models.ts
Labels: Complexity: Low, Type: Feature

#1062 feat(egld): initial implementation
  .github/workflows/ci.yml
  .pnp.js
  .yarn/cache/@babel-runtime-npm-7.13.2-372de9fc27-2.zip
  .yarn/cache/@elrondnetwork-bls-wasm-npm-0.3.3-751df142ad-2.zip
  .yarn/cache/@elrondnetwork-elrond-core-js-npm-2.1.0-1ccc11aa8f-2.zip
  .yarn/cache/assert-npm-2.0.0-ef73bc19f5-2.zip
  .yarn/cache/bech32-npm-2.0.0-ad98b7dd79-2.zip
  .yarn/cache/bls-signatures-npm-0.2.5-2b4387e166-2.zip
  .yarn/cache/ed25519-hd-key-npm-1.2.0-6456d8d35b-2.zip
  .yarn/cache/es6-object-assign-npm-1.1.0-0565318480-2.zip
  .yarn/cache/is-nan-npm-1.3.2-a087d31a28-2.zip
  .yarn/cache/jssha-npm-2.4.2-9a91eba44b-2.zip
  .yarn/cache/perf_hooks-npm-0.0.1-414363b18d-2.zip
  .yarn/cache/tweetnacl-util-npm-0.15.1-1a24bc512a-2.zip
  .yarn/install-state.gz
  .yarnrc.yml
  packages/platform-sdk-egld/LICENSE
  packages/platform-sdk-egld/README.md
  packages/platform-sdk-egld/banner.png
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-egld/src/dto/index.ts
  packages/platform-sdk-egld/src/dto/signed-transaction.ts
  packages/platform-sdk-egld/src/dto/transaction.ts
  packages/platform-sdk-egld/src/dto/wallet.ts
  packages/platform-sdk-egld/src/index.ts
  packages/platform-sdk-egld/src/manifest.ts
  packages/platform-sdk-egld/src/networks/egld/mainnet.ts
  packages/platform-sdk-egld/src/networks/egld/testnet.ts
  packages/platform-sdk-egld/src/schema.ts
  packages/platform-sdk-egld/src/service-provider.ts
  packages/platform-sdk-egld/src/services/client.ts
  packages/platform-sdk-egld/src/services/data-transfer-object.ts
  packages/platform-sdk-egld/src/services/fee.ts
  packages/platform-sdk-egld/src/services/helpers.ts
  packages/platform-sdk-egld/src/services/identity.test.ts
  packages/platform-sdk-egld/src/services/identity/address.ts
  packages/platform-sdk-egld/src/services/identity/index.ts
  packages/platform-sdk-egld/src/services/identity/keys.ts
  packages/platform-sdk-egld/src/services/identity/private-key.ts
  packages/platform-sdk-egld/src/services/identity/public-key.ts
  packages/platform-sdk-egld/src/services/identity/wif.ts
  packages/platform-sdk-egld/src/services/index.ts
  packages/platform-sdk-egld/src/services/known-wallets.ts
  packages/platform-sdk-egld/src/services/ledger.ts
  packages/platform-sdk-egld/src/services/link.ts
  packages/platform-sdk-egld/src/services/message.ts
  packages/platform-sdk-egld/src/services/multi-signature.ts
  packages/platform-sdk-egld/src/services/peer.ts
  packages/platform-sdk-egld/src/services/transaction.ts
  packages/platform-sdk-egld/test/fixtures/identity.ts
  packages/platform-sdk-egld/test/helpers.ts
  packages/platform-sdk-egld/tsconfig.json
  yarn.lock
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#1066 feat(egld): implement transfer signing and broadcasting
  packages/platform-sdk-ada/src/services/client.ts
  packages/platform-sdk-egld/src/services/client.ts
  packages/platform-sdk-egld/src/services/transaction.ts
Labels: Complexity: Medium, Status: Needs Review

#1068 refactor: omit days from fee requests
  .yarn/install-state.gz
  packages/platform-sdk-ada/src/services/fee.ts
  packages/platform-sdk-ark/src/services/fee.test.ts
  packages/platform-sdk-ark/src/services/fee.ts
  packages/platform-sdk-atom/src/services/fee.ts
  packages/platform-sdk-avax/src/services/fee.ts
  packages/platform-sdk-btc/src/services/fee.ts
  packages/platform-sdk-dot/src/services/fee.ts
  packages/platform-sdk-egld/src/services/fee.ts
  packages/platform-sdk-eos/src/services/fee.ts
  packages/platform-sdk-eth/src/services/fee.test.ts
  packages/platform-sdk-eth/src/services/fee.ts
  packages/platform-sdk-lsk/src/services/fee.test.ts
  packages/platform-sdk-lsk/src/services/fee.ts
  packages/platform-sdk-neo/src/services/fee.ts
  packages/platform-sdk-profiles/src/environment/services/fee-service.ts
  packages/platform-sdk-trx/src/services/fee.ts
  packages/platform-sdk-xlm/src/services/fee.ts
  packages/platform-sdk-xrp/src/services/fee.ts
  packages/platform-sdk/src/contracts/coins/fee.ts
Labels: Complexity: Low, Status: Needs Review

#1069 release: 3.0.0
  .github/workflows/cf.yml
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Undetermined, Status: Needs Review

#1070 fix(egld): use `EGLD` as export name
  packages/platform-sdk-egld/src/index.ts
Labels: Complexity: Low, Status: Needs Review

#1071 feat(egld): implement `ClientService#wallet`
  packages/platform-sdk-egld/src/dto/wallet.ts
  packages/platform-sdk-egld/src/services/client.ts
Labels: Complexity: Low, Status: Needs Review

#1073 refactor(egld): adjust DTOs and some API paths
  .yarn/build-state.yml
  .yarn/install-state.gz
  packages/platform-sdk-egld/src/dto/signed-transaction.ts
  packages/platform-sdk-egld/src/dto/transaction.ts
  packages/platform-sdk-egld/src/dto/wallet.ts
  packages/platform-sdk-egld/src/networks/egld/mainnet.ts
  packages/platform-sdk-egld/src/networks/egld/testnet.ts
  packages/platform-sdk-egld/src/services/client.ts
  packages/platform-sdk-egld/src/services/link.ts
Labels: Complexity: Medium, Status: Needs Review

#1074 release: 3.0.3
  .yarn/install-state.gz
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
  packages/platform-sdk/src/dto/peer.test.ts
Labels: Complexity: Undetermined, Status: Needs Review

#1075 fix(egld): expect `egld.mainnet` or `egld.testnet` as networks
  packages/platform-sdk-egld/src/schema.ts
  packages/platform-sdk-egld/test/helpers.ts
Labels: Complexity: Low, Status: Needs Review

#1076 fix(egld): expect address or list of addresses for `ClientService#transactions`
  packages/platform-sdk-egld/src/networks/egld/testnet.ts
  packages/platform-sdk-egld/src/services/client.test.ts
  packages/platform-sdk-egld/src/services/client.ts
  packages/platform-sdk-egld/test/fixtures/client/transaction.json
  packages/platform-sdk-egld/test/fixtures/client/transactions.json
  packages/platform-sdk-egld/test/fixtures/client/wallet.json
Labels: Complexity: Medium, Status: Needs Review

#1072 fix(profiles): adjust validation of plugins
  .yarn/install-state.gz
  packages/platform-sdk-profiles/src/profiles/profile.ts
Labels: Complexity: Low, Type: Bugfix

#1077 release: 3.0.6
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-egld/src/services/client.test.ts
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
  packages/platform-sdk/src/dto/peer.test.ts
Labels: Complexity: Undetermined, Status: Needs Review

#1078 fix(egld): normalise numeric values to satoshis
  packages/platform-sdk-egld/src/dto/signed-transaction.ts
  packages/platform-sdk-egld/src/dto/transaction.ts
  packages/platform-sdk-egld/src/dto/wallet.ts
Labels: Complexity: Low, Status: Needs Review

#1079 release: 3.0.7
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Undetermined, Status: Needs Review

#1080 fix(egld): normalise fees to satoshi
  packages/platform-sdk-egld/src/dto/signed-transaction.ts
  packages/platform-sdk-egld/src/dto/transaction.ts
  packages/platform-sdk-egld/src/networks/egld/testnet.ts
Labels: Complexity: Low, Status: Needs Review

#1081 release: 3.0.8
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Status: Needs Review

#1082 fix(egld): link `blocks` to `miniblocks`
  packages/platform-sdk-egld/src/networks/egld/mainnet.ts
  packages/platform-sdk-egld/src/networks/egld/testnet.ts
  packages/platform-sdk-egld/src/services/link.ts
Labels: Complexity: Low, Status: Needs Review

#1083 fix(egld): treat transaction timestamp as unix
  packages/platform-sdk-egld/src/dto/transaction.ts
Labels: Complexity: Low, Status: Needs Review

#1084 release: 3.0.10
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Status: Needs Review

#1085 feat(eth): retrieve fees from `ethgas.watch`
  .yarn/install-state.gz
  packages/platform-sdk-eth/src/services/fee.test.ts
  packages/platform-sdk-eth/src/services/fee.ts
  packages/platform-sdk-eth/test/fixtures/client/fees.json
Labels: Complexity: Medium, Status: Needs Review

#1086 refactor(profiles): store plugins with an internal UUID
  packages/platform-sdk-profiles/src/plugins/plugin-repository.test.ts
  packages/platform-sdk-profiles/src/plugins/plugin-repository.ts
Labels: Complexity: Low, Status: Needs Review

#1087 release: 3.0.12
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Status: Needs Review

#1089 perf(eth-indexer): add missing block and transaction indices
  .yarn/build-state.yml
  .yarn/install-state.gz
  packages/platform-sdk-eth-indexer/src/database.ts
Labels: Complexity: Low, Status: Needs Review

#1091 feat(profiles): implement `ReadWriteWallet#displayName`
  packages/platform-sdk-profiles/src/wallets/wallet.models.ts
  packages/platform-sdk-profiles/src/wallets/wallet.test.ts
  packages/platform-sdk-profiles/src/wallets/wallet.ts
Labels: Complexity: Low, Type: Feature

#1092 chore(profiles): add `ProfileSetting.DashboardTransactionHistory`
  packages/platform-sdk-profiles/src/profiles/profile.models.ts
Labels: Complexity: Low, Type: Task

#1093 release: 3.0.15
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Status: Needs Review

#1094 fix(profiles): include ID in plugin data
  .yarn/install-state.gz
  packages/platform-sdk-profiles/src/plugins/plugin-repository.test.ts
  packages/platform-sdk-profiles/src/plugins/plugin-repository.ts
Labels: Complexity: Low, Status: Needs Review

#1090 refactor(dot): use SQLite as database engine
  .pnp.js
  .yarn/cache/@elastic-elasticsearch-npm-7.10.0-74c9a2bc6d-197801d015.zip
  .yarn/cache/hpagent-npm-0.1.1-6e908aa2dd-c68850c445.zip
  .yarn/cache/secure-json-parse-npm-2.3.0-a73199914c-412ba05613.zip
  .yarn/install-state.gz
  packages/platform-sdk-dot-indexer/bin/meow.js
  packages/platform-sdk-dot-indexer/bin/run
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot-indexer/src/database.ts
  packages/platform-sdk-dot-indexer/src/helpers.ts
  packages/platform-sdk-dot-indexer/src/index.ts
  yarn.lock
Labels: Complexity: High, Status: Needs Review, Type: Feature

#1095 refactor(eth-indexer): only store data that is required for API consumption
  packages/platform-sdk-eth-indexer/src/database.ts
Labels: Complexity: Medium, Status: Needs Review

#1096 release: 3.0.18
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Status: Needs Review

#1097 feat(eth-server): initial implementation
  .pnp.js
  .yarn/install-state.gz
  packages/platform-sdk-eth-server/LICENSE
  packages/platform-sdk-eth-server/README.md
  packages/platform-sdk-eth-server/banner.png
  packages/platform-sdk-eth-server/bin/meow.js
  packages/platform-sdk-eth-server/bin/run
  packages/platform-sdk-eth-server/bin/subscribe.js
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth-server/src/helpers.ts
  packages/platform-sdk-eth-server/src/index.ts
  packages/platform-sdk-eth-server/tsconfig.json
  yarn.lock
Labels: Complexity: High, Status: Needs Review

#1098 fix(eth-indexer): remove trailing commas from SQL migration
  packages/platform-sdk-eth-indexer/src/database.ts
Labels: Complexity: Low, Status: Needs Review

#1099 release: 3.0.20
  .yarn/install-state.gz
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Status: Needs Review

#1101 feat(eth-server): implement wallet endpoint
  .pnp.js
  .yarn/install-state.gz
  packages/platform-sdk-eth-server/bin/meow.js
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth-server/src/helpers.ts
  packages/platform-sdk-eth-server/src/index.ts
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review

#1102 feat(eth-server): implement transaction broadcasting
  .pnp.js
  .yarn/install-state.gz
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth-server/src/index.ts
  yarn.lock
Labels: Complexity: Low, Status: Needs Review

#1103 feat(eth-server): return state information from root path
  packages/platform-sdk-eth-server/src/index.ts
Labels: Complexity: Low, Status: Needs Review

#1104 feat(eth-server): validate path parameters
  packages/platform-sdk-eth-server/src/index.ts
Labels: Complexity: Low, Status: Needs Review

#1105 fix(eth-server): strip out unknown parameters
  packages/platform-sdk-eth-server/src/index.ts
Labels: Complexity: Low, Status: Needs Review

#1106 release: 3.0.26
  CHANGELOG.md
  packages/platform-sdk-ada/package.json
  packages/platform-sdk-ark/package.json
  packages/platform-sdk-atom/package.json
  packages/platform-sdk-avax/package.json
  packages/platform-sdk-btc-indexer/package.json
  packages/platform-sdk-btc/package.json
  packages/platform-sdk-coincap/package.json
  packages/platform-sdk-coingecko/package.json
  packages/platform-sdk-crypto/package.json
  packages/platform-sdk-cryptocompare/package.json
  packages/platform-sdk-dot-indexer/package.json
  packages/platform-sdk-dot/package.json
  packages/platform-sdk-egld/package.json
  packages/platform-sdk-eos/package.json
  packages/platform-sdk-eth-indexer/package.json
  packages/platform-sdk-eth-server/package.json
  packages/platform-sdk-eth/package.json
  packages/platform-sdk-http-axios/package.json
  packages/platform-sdk-http-bent/package.json
  packages/platform-sdk-http-got/package.json
  packages/platform-sdk-http-ky/package.json
  packages/platform-sdk-http-node-fetch/package.json
  packages/platform-sdk-intl/package.json
  packages/platform-sdk-json-rpc/package.json
  packages/platform-sdk-lsk/package.json
  packages/platform-sdk-markets/package.json
  packages/platform-sdk-neo/package.json
  packages/platform-sdk-news/package.json
  packages/platform-sdk-profiles/package.json
  packages/platform-sdk-support/package.json
  packages/platform-sdk-trx/package.json
  packages/platform-sdk-xlm/package.json
  packages/platform-sdk-xrp/package.json
  packages/platform-sdk/package.json
Labels: Complexity: Medium, Status: Needs Review

#1110 chore: create changelog for 2.x
  CHANGELOG-2.X.md
  CHANGELOG.md
Labels: Complexity: High, Status: Needs Review

#1112 fix(eth-server): allow block identifier to be number or hash
  packages/platform-sdk-eth-server/src/index.ts
Labels: Complexity: Low, Status: Needs Review
